# Modular addition experiment configuration

grid:
  # Number of unique training pairs
  T: [32, 64, 128]
  # Modulus for addition task
  m: [97]
  # Batch sizes to sweep
  batch_size: [64, 128]
  # Random seeds for reproducibility
  seeds: [0, 1, 2]

recipe:
  - name: mod_add
    task: mod_add
    model: mlp
    train_steps: 1000
