# Tiny grammar in-context learning experiment configuration

grid:
  # Maximum length of strings
  L: [6, 8]
  # Number of demonstrations per example
  k: [2]
  # Random seeds for reproducibility
  seeds: [0, 1, 2]

recipe:
  - name: tiny_grammar_icl
    task: tiny_grammar_icl
    model: transformer
    train_steps: 1000
